import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Clock3, FilePlus2, FolderOpen, Plus, Search, ShieldCheck } from 'lucide-react';
import type { CaseRecord } from '../lib/workspace';
import { Badge, dateOnly, Empty, PageHead } from './ui';

export default function Queue({ cases, loading }: { cases: CaseRecord[]; loading: boolean }) {
  const [filter, setFilter] = useState('all');
  const [query, setQuery] = useState('');
  const [sort, setSort] = useState('updated');
  const reviewed = cases.filter(c => c.phase === 'decided').length;
  const awaiting = cases.filter(c => c.phase === 'assessed').length;
  const inProgress = cases.length - reviewed - awaiting;
  const filtered = cases.filter(c => (filter === 'all' || (filter === 'review' && c.phase === 'assessed') || (filter === 'progress' && ['draft', 'requirements'].includes(c.phase)) || (filter === 'decided' && c.phase === 'decided')) && `${c.title} ${c.tenderReference} ${c.bidderName}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === 'deadline' ? (a.deadline || '9999').localeCompare(b.deadline || '9999') : b.updatedAt.localeCompare(a.updatedAt));
  const closing = cases.filter(c => c.deadline && c.phase !== 'decided').sort((a, b) => a.deadline!.localeCompare(b.deadline!)).slice(0, 3);
  return <><PageHead label="Procurement workspace / Overview" title="Verification queue" description="A clear view of the evidence. A considered decision on every bid." action={<button className="button primary" onClick={() => { window.location.hash = 'new'; }}><Plus size={16} />New case</button>} />
    <div className="ledger-stats"><div><span className="stat-label">Open cases</span><strong>{String(cases.length - reviewed).padStart(2, '0')}</strong><span className="stat-note">in your workspace</span></div><div><span className="stat-label"><span className="status-dot amber" />Awaiting decision</span><strong>{String(awaiting).padStart(2, '0')}</strong><span className="stat-note">ready for officer review</span></div><div><span className="stat-label">In preparation</span><strong>{String(inProgress).padStart(2, '0')}</strong><span className="stat-note">intake &amp; checklist review</span></div><div><span className="stat-label"><span className="status-dot green" />Decisions recorded</span><strong>{String(reviewed).padStart(2, '0')}</strong><span className="stat-note">with a written reason</span></div></div>
    <div className="queue-layout"><section className="queue-section"><div className="section-topline"><h2>Your case register</h2><span className="mono muted">{String(cases.length).padStart(2, '0')} RECORDS</span></div><div className="filter-tabs" aria-label="Filter cases">{[['all', 'All cases', cases.length], ['review', 'Awaiting decision', awaiting], ['progress', 'In preparation', inProgress], ['decided', 'Decided', reviewed]].map(([value, label, count]) => <button key={value} className={filter === value ? 'active' : ''} onClick={() => setFilter(String(value))} aria-pressed={filter === value}>{label}<span>{count}</span></button>)}</div><div className="table-toolbar"><label className="search-field"><Search size={16} /><input aria-label="Search cases" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search bidder, tender or reference…" /><kbd>/</kbd></label><label className="sort-label">Sort by<select aria-label="Sort cases" value={sort} onChange={e => setSort(e.target.value)}><option value="updated">Latest activity</option><option value="deadline">Closing date</option></select></label></div>
    <div className="table-frame"><table className="case-table"><thead><tr><th>Bidder / Tender</th><th>Assessment</th><th>Review status</th><th>Closing date</th><th><span className="sr-only">Open case</span></th></tr></thead>{filtered.length > 0 && <tbody>{filtered.map(c => <tr key={c.id}><td><a className="case-name" href={`#case/${c.id}`}>{c.bidderName}</a><span className="table-subtitle">{c.title}</span><span className="table-ref">{c.tenderReference}</span></td><td>{c.result ? <><span className="table-score">{c.result.decision.score.percentage}<small>/ 100</small></span><span className="table-subtitle">{c.result.decision.score.is_final ? 'Validated score' : 'Provisional score'}</span></> : <span className="muted">Not assessed</span>}</td><td><Badge state={c.decision?.outcome || c.phase} />{c.result && !c.decision && <span className="table-subtitle">{c.result.findings.length} finding{c.result.findings.length !== 1 ? 's' : ''} to examine</span>}</td><td className="date-cell">{c.deadline ? dateOnly(c.deadline) : <span className="muted">Not recorded</span>}</td><td><a className="icon-button" aria-label={`Open case for ${c.bidderName}`} href={`#case/${c.id}`}><ArrowUpRight size={18} /></a></td></tr>)}</tbody>}</table>{!filtered.length && <Empty title={loading ? 'Opening your workspace…' : cases.length ? 'No cases match this view.' : 'Your next decision starts here.'} action={!loading && (cases.length ? <button className="button secondary" onClick={() => { setQuery(''); setFilter('all'); }}>Clear filters</button> : <a className="button primary" href="#new"><FilePlus2 size={16} />Open your first case<ArrowRight size={15} /></a>)}>{loading ? 'Reading the case register saved in this browser.' : cases.length ? 'Try another bidder name, tender reference, or status.' : 'Add a tender and bidder submission to build a review grounded in the original evidence.'}</Empty>}</div><div className="register-footer"><span>{filtered.length} of {cases.length} cases</span><span><FolderOpen size={13} />Saved in this browser</span></div></section>
    <aside className="queue-aside"><section className="review-principle"><div className="aside-heading"><ShieldCheck size={19} strokeWidth={1.4} /><span className="eyebrow">The standard of review</span></div><h2>Evidence before<br /><em>judgement.</em></h2><p>Every finding should lead back to a clause, a document, and a clear explanation.</p><div className="principle-rule" /><div className="principle-item"><span>01</span><div><strong>Read the requirement</strong><small>Keep the original clause in view.</small></div></div><div className="principle-item"><span>02</span><div><strong>Examine the source</strong><small>Separate submissions from verification.</small></div></div><div className="principle-item"><span>03</span><div><strong>Record the reasoning</strong><small>Make the decision traceable.</small></div></div><div className="seal-line"><span>TRUST SETU</span><span>REVIEW WITH REASON</span></div></section>
    <section className="deadline-section"><div className="section-topline"><h3><Clock3 size={15} />Closing dates</h3><span className="mono muted">OPEN CASES</span></div>{closing.length ? closing.map(c => <a className="deadline-case" href={`#case/${c.id}`} key={c.id}><span>{c.title}<small>{c.tenderReference}</small></span><strong>{dateOnly(c.deadline!)}<ArrowUpRight size={14} /></strong></a>) : <p className="aside-muted">Closing dates entered in your cases will appear here.</p>}</section><p className="aside-footnote">The system assesses the evidence.<br />The procurement officer makes the decision.</p></aside></div></>;
}
